lugares_yum = [
    "céu", "discoteca", "espaço", "cosmos", "praia", "montanha", "floresta", "cidade", "deserto", "lago", 
    "oceano", "ilha", "polo norte", "polo sul", "cachoeira", "vulcão", "selva", "savanas", "planície", 
    "caverna", "mar", "rio", "casa", "apartamento", "quintal", "sótão", "porão", "castelo", "templo", 
    "palácio", "torre", "fortaleza", "fazenda", "floresta tropical", "biblioteca", "escola", "universidade", 
    "hospital", "igreja", "mesquita", "templo budista", "sinagoga", "parque", "cinema", "museu", "teatro", 
    "shopping", "restaurante", "hotel", "aeroporto", "estação de trem", "porto", "rodoviária", "praça", 
    "rua", "avenida", "ponte", "estádio", "ginásio", "clube", "bar", "praia deserta", "coral", "mercado", 
    "feira", "zona rural", "subúrbio", "centro da cidade", "casa de campo", "casa de praia", "pântano", 
    "manguezal", "pantanal", "antártida", "áfrica", "ásia", "europa", "américa do sul", "américa do norte", 
    "oceania", "austrália", "brasil", "goiânia", "nova york", "paris", "londres", "berlim", "tóquio", 
    "seul", "pequim", "mumbai", "deli", "cairo", "mexico city", "los angeles", "sydney", "miami", 
    "singapura", "dubai", "las vegas", "rio de janeiro", "são paulo", "buenos aires", "montevidéu", 
    "bogotá", "lima", "toronto", "vancouver", "caribe", "hawaii", "ilhas maldivas", "ilhas seychelles", 
    "ilhas canárias", "ilhas galápagos", "ilha de páscoa", "ilha de madagascar", "ilha de marajó", 
    "ilha do mel", "ilha grande", "ilha de san andrés", "ilhabela", "ilhéus", "ilha de creta", "ilha de chipre", 
    "ilhas baleares", "ilha da madeira", "ilhas bermudas", "ilhas maurício", "grécia", "egito", 
    "jordânia", "turquia", "croácia", "tailândia", "vietnam", "cambodja", "filipinas", "malásia", 
    "indonésia", "tailândia", "aruba", "jamaica", "república dominicana", "ilhas fiji", "ilhas solomon", 
    "nova zelândia", "polinésia francesa", "ilhas cook", "ilhas virgens", "samoa", "guam", "ilhas marianas", 
    "ilhas samoa americana", "ilhas carolinas", "ilhas das pitcairn", "ilhas marshall", "ilhas kiribati", 
    "ilhas palau", "ilhas comores", "ilhas malvinas", "ilhas geórgia do sul", "ilhas shetland", 
    "ilhas faroé", "ilhas faial", "ilhas açores", "ilhas cabo verde", "ilhas flores", "ilha das flores", 
    "ilhas boa vista", "ilha de são vicente", "ilhas madeirenses", "ilhas canárias", "madeira", 
    "ilhas dos açores", "ilhas de man", "ilhas geórgia do sul", "ilhas santa helena", "ilhas de trindade", 
    "ilha de navassa", "ilha de barbudas", "ilha de antiguas", "ilha de são cristóvão", "ilhas nevis", 
    "ilhas granadinas", "ilha de dominica", "ilha de são vicente", "ilhas barbados", "ilhas santa lucia", 
    "ilha de grenada", "ilhas são bartolomeu", "ilhas sankt martin", "ilhas são joão", "ilhas bvis", 
    "ilhas guadalupe", "ilhas martinica", "ilha de montserrat", "ilhas caicos", "ilhas turks", "ilha de cayman", 
    "ilha de cocos", "ilha de keeling", "ilhas andaman", "ilhas nicobar", "ilha de phuket", "ilha de borneo", 
    "ilhas molucas", "ilhas lípari", "ilhas eólias", "ilhas pelágias", "ilha de pantelária", "ilha de lámpedusa", 
    "ilhas aland", "ilhas de gotlândia", "ilhas hiiumaa", "ilha de saaremaa", "ilhas estonianas", "ilhas de bornholm", 
    "ilhas falster", "ilha de zelandia", "ilhas mon", "ilhas faroé", "ilhas orcadia", "ilhas shetland", 
    "ilhas hebridas", "ilhas hébridas externas", "ilha de sky", "ilha de lewis", "ilha de barra", "ilhas inner hebrides", 
    "ilhas outer hebrides", "ilhas de skye", "ilhas arran", "ilhas bute", "ilhas clyde", "ilhas guernsey", 
    "ilhas jersey", "ilhas ilha de wight", "ilha de anglesey", "ilhas holy", "ilhas de lindisfarne", 
    "ilhas scilly", "ilhas alcatraz", "ilhas de alcatraz", "ilha de alcatraz", "ilha do sol", "ilha da lua"
]