adjetivos = [
    "vibrante", "brilhante", "luzente", "radiante", "intenso", "colorido", "fascinante", 
    "magnífico", "deslumbrante", "maravilhoso", "incrível", "extraordinário", "fantástico", 
    "impressionante", "notável", "singular", "diverso", "original", "autêntico", "exclusivo", 
    "enigmático", "misterioso", "cativante", "sedutor", "atrativo", "encantador", 
    "charmoso", "estonteante", "surpreendente", "emocionante", "apaixonante", "dinâmico", 
    "vital", "energético", "radiante", "sereno", "tranquilo", "calmo", "harmonioso", 
    "suave", "delicado", "brando", "gentil", "carinhoso", "afetuoso", "terno", 
    "afável", "amigável", "simpático", "bondoso", "generoso", "solidário", "acolhedor", 
    "acolhedor", "amável", "sincero", "honesto", "leal", "fiel", "justo", 
    "equilibrado", "pacífico", "tranquilo", "respeitoso", "honrado", "valente", 
    "corajoso", "destemido", "audacioso", "arrojado", "valioso", "precioso", "imperdível", 
    "tímido", "reservado", "discreto", "modesto", "humilde", "reflexivo", "pensativo", 
    "introspectivo", "analítico", "crítico", "curioso", "investigativo", "perceptivo", 
    "astuto", "sagaz", "inteligente", "perspicaz", "brilhante", "genial", "criativo", 
    "inovador", "inventivo", "artístico", "cultural", "educativo", "formativo", 
    "enriquecedor", "aprendizado", "teórico", "prático", "metódico", "organizado", 
    "eficiente", "produtivo", "rápido", "ágil", "flexível", "adaptável", "resiliente", 
    "determinado", "persistente", "tenaz", "firme", "estável", "sólido", "consistente", 
    "confiável", "responsável", "disciplinado", "puntual", "meticuloso", "rigoroso", 
    "preciso", "detalhista", "claro", "transparente", "completo", "abrangente", 
    "sustentável", "ecológico", "verde", "limpo", "saudável", "natural", "orgânico", 
    "benéfico", "nutritivo", "revigorante", "curativo", "terapêutico", "confortável", 
    "prazeroso", "agradável", "divertido", "interessante", "empolgante", "instigante", 
    "desafiador", "inspirador", "motivador", "encorajador", "refrescante", "inovador", 
    "surpreendente", "empolgante", "enérgico", "efervescente", "vitalizante", "impactante", 
    "transformador", "revolucionário", "pioneiro", "avançado", "futuro", "visionário", 
    "tecnológico", "digital", "virtual", "inteligente", "conectado", "adaptável", 
    "moderno", "contemporâneo", "clássico", "atemporal", "cultural", "histórico", 
    "tradicional", "folclórico", "popular", "comercial", "artesanal", "manual", 
    "exótico", "tropical", "urbano", "rural", "pitoresco", "tranquilo", "belo", 
    "charmoso", "vivo", "radiante", "luxuoso", "elegante", "sofisticado", "minimalista", 
    "extrovertido", "introvertido", "nobre", "equitativo", "plural", "diverso", 
    "inclusivo", "acessível", "abrangente", "universal", "cósmico", "planetário", 
    "global", "local", "regional", "individual", "coletivo", "familiar", "feminino", 
    "masculino", "neutro", "afro", "latino", "asiático", "europeu", "multicultural", 
    "cosmopolita", "integrador", "emergente", "desenvolvido", "crescente", "estável"
]