substantivos = [
    "energia", "arte", "forma", "galáxia", "luz", "tecnologia", "movimento", "fantasia", "padrão", 
    "tempo", "espaço", "vida", "natureza", "universo", "planeta", "estrela", "sistema", "criatividade", 
    "força", "potência", "inteligência", "informação", "sabedoria", "amor", "paixão", "ódio", "medo", 
    "esperança", "destino", "sorte", "coragem", "amizade", "solidão", "tristeza", "alegria", "felicidade", 
    "memória", "pensamento", "idéia", "opinião", "sugestão", "proposta", "projeto", "invenção", "descoberta", 
    "ciência", "arte", "literatura", "filosofia", "música", "pintura", "escultura", "dança", "teatro", 
    "cinema", "fotografia", "poesia", "linguagem", "palavra", "símbolo", "imagem", "som", "cor", "linhas", 
    "textura", "volume", "gravidade", "massa", "velocidade", "aceleração", "força", "energia", "fricção", 
    "atrito", "pressão", "temperatura", "calor", "frio", "eletricidade", "magnetismo", "radiação", 
    "fóton", "átomo", "molécula", "célula", "organismo", "espécie", "animal", "vegetal", "mineral", 
    "matéria", "substância", "líquido", "gás", "sólido", "vapor", "plasma", "densidade", "fluidez", 
    "mundo", "continente", "país", "cidade", "bairro", "vila", "comunidade", "família", "indivíduo", 
    "grupo", "sociedade", "cultura", "civilização", "história", "tradição", "costume", "hábito", 
    "religião", "fé", "espiritualidade", "ritual", "cerimônia", "festa", "celebração", "evento", 
    "ocasião", "congresso", "encontro", "reunião", "assembleia", "conferência", "simposium", 
    "exposição", "feira", "mercado", "loja", "empresa", "indústria", "fábrica", "comércio", 
    "produto", "serviço", "mercadoria", "capital", "dinheiro", "moeda", "nota", "cartão", 
    "crédito", "débito", "pagamento", "compra", "venda", "troca", "negócio", "contrato", 
    "acordo", "aliança", "cooperação", "parceria", "conflito", "guerra", "paz", "armistício", 
    "vitória", "derrota", "competição", "disputa", "jogo", "esporte", "atividade", "trabalho", 
    "emprego", "ocupação", "carreira", "profissão", "cargo", "função", "responsabilidade", 
    "papel", "missão", "objetivo", "meta", "intenção", "vontade", "desejo", "necessidade", 
    "sonho", "ambição", "plano", "estratégia", "tática", "manobra", "ação", "movimento", 
    "gesto", "atitude", "comportamento", "hábito", "rotina", "costume", "modo", "jeito", 
    "maneira", "forma", "estrutura", "organização", "sistema", "rede", "mecanismo", 
    "processo", "função", "operação", "execução", "realização", "criação", "produção", 
    "construção", "destruição", "transformação", "mudança", "evolução", "crescimento", 
    "desenvolvimento", "progresso", "avanço", "retrocesso", "declínio", "queda", "aumento", 
    "diminuição", "redução", "expansão", "compressão", "distorção", "equilíbrio", "desordem", 
    "caos", "sistema", "ordem", "regra", "lei", "norma", "princípio", "direito", "justiça", 
    "moral", "ética", "responsabilidade", "dever", "obrigação", "liberdade", "autonomia", 
    "dependência", "controle", "poder", "autoridade", "liderança", "domínio", "influência", 
    "impacto", "efeito", "resultado", "consequência", "causa", "origem", "motivo", "razão", 
    "fundamento", "base", "suporte", "apoio", "estrutura", "alicerce", "plataforma", "conexão", 
    "vínculo", "ligação", "comunicação", "interação", "diálogo", "discussão", "conversa", 
    "negociação", "acordo", "aliança", "tratado", "pacto", "união", "associação", "coalizão", 
    "parceria", "colaboração", "cooperação", "ajuda", "assistência", "socorro", "apoio", 
    "salvamento", "resgate", "proteção", "segurança", "defesa", "ataque", "investida", 
    "ação", "reação", "resposta", "solução", "decisão", "escolha", "opção", "alternativa", 
    "chance", "oportunidade", "possibilidade", "probabilidade", "certeza", "dúvida", "incerteza", 
    "risco", "perigo", "ameaça", "desafio", "obstáculo", "barreira", "limite", "fronteira"
]