preposicoes = [
    "sob", "no", "em", "com", "para", "de", "a", "por", "até", "contra", "sobre", 
    "entre", "após", "perante", "diante de", "ao lado de", "perto de", "longe de", 
    "dentro de", "fora de", "acima de", "abaixo de", "atrás de", "na frente de", 
    "junto a", "ao redor de", "em cima de", "embaixo de", "ao redor de", "à direita de", 
    "à esquerda de", "em volta de", "em face de", "em meio a", "em direção a", "por causa de", 
    "por meio de", "graças a", "em razão de", "em virtude de", "em função de", "em detrimento de", 
    "a favor de", "contra", "em lugar de", "em troca de", "à espera de", "por conta de", 
    "ao longo de", "antes de", "depois de", "durante", "ao contrário de", "a partir de", 
    "a fim de", "por volta de", "por trás de", "em vez de", "com base em", "a bordo de", 
    "em face a", "acerca de", "a respeito de", "com respeito a", "a despeito de", "em relação a", 
    "no lugar de", "a caminho de", "a favor de", "de acordo com", "à procura de", 
    "por intermédio de", "em busca de", "ao invés de", "a par de", "em consonância com", 
    "de frente para", "de encontro a", "em conformidade com", "em oposição a", "ao encontro de", 
    "de acordo com", "em prol de", "a bem de", "à mercê de", "à maneira de", "na base de", 
    "de modo a", "de forma a", "de maneira a", "sob o pretexto de", "à custa de", "em nome de", 
    "sob pena de", "sob a condição de", "por causa de", "a despeito de", "à medida que", 
    "ao passo que", "por meio de", "com vista a", "no tocante a", "à luz de", "em decorrência de", 
    "em sequência a", "a respeito de", "por obra de", "sob a influência de", "a título de", 
    "em alusão a", "em concordância com", "a pretexto de", "em conformidade a", "à altura de", 
    "a julgar por", "sob efeito de", "sob o impacto de", "por motivo de", "em relação a", 
    "em comparação a", "com relação a", "à semelhança de", "em alusão a", "em referência a", 
    "no decorrer de", "no sentido de", "com o objetivo de", "à exceção de", "no caso de", 
    "à sombra de", "à beira de", "por ocasião de", "por força de", "em consequência de", 
    "de conformidade com", "por falta de", "em companhia de", "sob a égide de", "ao longo de", 
    "em detrimento de", "a pretexto de", "a sombra de", "a caminho de", "de acordo com", 
    "ao abrigo de", "a despeito de", "à custa de", "à disposição de", "em favor de", 
    "à frente de", "a cargo de", "em contrapartida a", "de acordo com", "em consonância com", 
    "em consonância a", "de encontro a", "ao lado de", "diante de", "ao pé de", "debaixo de", 
    "defronte de", "de acordo com", "em virtude de", "em vez de", "em direção a", "ao pé de", 
    "ao fundo de", "a despeito de", "ao redor de", "à custa de", "com base em", "em prol de", 
    "em torno de", "ao encontro de", "em contraste com", "de encontro a", "a fim de", "à medida de", 
    "com vista a", "em consideração a", "à semelhança de", "em companhia de", "à maneira de", 
    "à mercê de", "a partir de", "à luz de", "em vez de", "a pretexto de", "à sombra de", 
    "com exceção de", "em referência a", "por intermédio de", "ao sabor de", "em presença de", 
    "em conformidade com", "em função de", "com o intuito de", "sob os auspícios de", "a mando de", 
    "ao rés de", "debaixo de", "acima de", "além de", "antes de", "ao contrário de", "ao redor de", 
    "dentro de", "fora de", "frente a", "junto a", "junto de", "no meio de", "por entre", 
    "por causa de", "em vista de", "no centro de", "ao pé de", "a despeito de", "por cima de", 
    "por baixo de", "em nome de", "a despeito de", "devido a", "à maneira de", "à moda de", 
    "à base de", "a exemplo de", "na qualidade de", "a tempo de", "a pretexto de", "a serviço de", 
    "à semelhança de", "à exceção de", "em nome de", "em via de", "a partir de", "em torno de"
]