tipos_de_coisas = [
    'bolo',
    'pão',
    'torta',
    'como fazer',
    'cookie',
    'brownie',
    'sorvete',
    'pizza',
    'pao',
    'quiche',
    'panqueca',
    'crepe',
    'muffin',
    'pudim',
    'gelatina',
    'pastel',
    'tapioca',
    'suco',
    'smoothie',
    'sanduíche',
    'salada',
    'prato principal',
    'molho',
    'caldo',
    'petisco',
    'aperitivo',
    'tapioca',
    'guisado',
    'risoto',
    'massa',
    'lasanha',
    'strogonoff',
    'omelete',
    'sopa',
    'cuscuz',
    'wrap',
    'cobertura',
    'fritada',
    'farofa',
    'tacos',
    'bolinho',
    'empada',
    'pão de queijo',
    'pudim',
    'berinjela à parmegiana',
    'esfiha',
    'churrasco',
    'receita de família',
    'receita vegana',
    'receita sem glúten',
    'receita low carb',
    'receita saudável'
]