verbos_agente = [
     "correr", "saltar", "nadar", "andar", "comer", "beber", "dormir", "acordar",
     "cair", "levantar", "sentar", "deitar", "pegar", "soltar", "jogar", "empurrar",
     "puxar", "construir", "destruir", "quebrar", "consertar", "pintar", "desenhar",
     "escrever", "ler", "ouvir", "falar", "cantar", "dançar", "tocar (instrumento)", "rir",
     "chorar", "respirar", "suar", "tremer", "congelar", "queimar", "brilhar", "cintilar",
     "piscar", "olhar", "sorrir", "franzir", "apontar", "gesticular", "agarrar", "abraçar",
     "beijar", "bater", "acariciar", "pensar", "imaginar", "sonhar", "lembrar", "esquecer",
     "aprender", "ensinar", "estudar", "calcular", "analisar", "criar", "inventar", "decidir",
     "escolher", "planejar", "organizar", "resolver", "questionar", "duvidar", "acreditar",
     "confiar", "temer", "odiar", "amar", "admirar", "respeitar", "desprezar", "invejar",
     "ansiar", "esperar", "desejar", "necessitar", "estar", "parecer", "sentir", "ter", "possuir",
     "precisar", "faltar", "sobrar", "caber", "conter", "ocupar", "pesar", "medir", "valer",
     "custar", "durar", "ser", "parecer", "sentir", "conhecer", "saber", "entender", "recordar",
     "esquecer", "acreditar", "confiar", "temer", "odiar", "amar", "admirar", "respeitar",
     "desprezar", "invejar", "transformar", "mudar", "alterar", "evoluir", "crescer", "diminuir",
     "expandir", "contrair", "derreter", "solidificar", "vaporizar", "condensar", "enferrujar",
     "oxidar", "apodrecer", "apoiar", "levantar", "abaixar", "aumentar", "diminuir", "acelerar",
     "desacelerar", "aprender", "ensinar", "mudar", "desenvolver", "melhorar", "piorar",
     "esquecer", "lembrar", "converter", "transformar", "falar", "dizer", "perguntar", "responder",
     "explicar", "descrever", "narrar", "discutir", "argumentar", "convencer", "persuadir",
     "ordenar", "proibir", "permitir", "sugerir", "aconselhar", "elogiar", "criticar", "agradecer",
     "pedir", "oferecer", "prometer", "mostrar", "apontar", "gesticular", "escrever", "desenhar",
     "sinalizar", "comunicar", "expressar", "transmitir", "ver", "observar", "notar", "perceber",
     "distinguir", "identificar", "reconhecer", "admirar", "ouvir", "escutar", "perceber", "distinguir",
     "identificar", "reconhecer", "tocar", "sentir", "perceber", "distinguir", "identificar",
     "provar", "saborear", "sentir", "distinguir", "identificar", "cheirar", "sentir", "perceber",
     "distinguir", "identificar", "conhecer", "encontrar", "visitar", "conversar", "discutir",
     "colaborar", "competir", "ajudar", "prejudicar", "amar", "odiar", "admirar", "respeitar",
     "desprezar", "invejar", "perdoar", "causar", "provocar", "gerar", "originar", "resultar",
     "depender", "influenciar", "determinar", "Estar", "haver", "existir", "Poder", "querer",
     "dever", "precisar", "ter que", "Afirmar", "negar", "questionar", "sugerir", "ordenar",
     "Acreditar", "duvidar", "pensar", "imaginar", "sonhar", "Amar", "odiar", "temer", "gostar",
     "não gostar", "Fazer", "construir", "criar", "destruir", "reparar", "caminhar", "passear",
     "ver", "olhar", "observar", "comer", "devorar", "saborear", "dar uma olhada",
     "tirar uma foto", "fazer uma pergunta", "passar o tempo", "experimentar", "analisar",
     "calcular", "hipotetizar", "pintar", "esculpir", "compor", "representar", "driblar",
     "chutar", "arremessar", "marcar", "programar", "hackear", "logar", "salvar", "curtir",
     "dar like", "compartilhar", "seguir", "controla", "flui", "acena", "conecta", "move"
     ]